// Generated by Wrangler by running `wrangler types`

interface Env {
  OAUTH_KV: KVNamespace;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  COOKIE_ENCRYPTION_KEY: string;
  HOSTED_DOMAIN: string;
  ALLOWED_EMAILS?: string;
  ALLOWED_DOMAINS?: string;
  ALIAS_PATHS?: string;
  PATH_EMAIL_MAP?: string;
  MCP_OBJECT: DurableObjectNamespace<import("./src/index").MyMCP>;
}